### ISSUE TITLE
Add crate for traits

### ISSUE THREAD

**Issue by sushisilence** [silence-laboratories/sl-crypto#2]
All our two party protocols use the `Round` and `PersistentObj` traits. (EdDSA and ECDSA). I'd like to add a crate for commonly used traits. Adding this two `sl-mpc-mate` behind "traits" feature seems overkill as we just want the traits and not all the other code from `sl-mpc-mate` 

I'd like to add a `sl-mpc-traits` crate in `sl-crypto`. 

WDYT @left-arm?

**Comment by left-arm** [comment]
Sounds good to me
